[colors.cursor]
cursor = "#E2C1A6"
text = "#2B353E"

[colors.primary]
background = "#2B353E"
foreground = "#E2C1A6"

[font]
size = 12.0

[font.bold]
family = "AnonymicePro Nerd Font"
style = "Bold"

[font.italic]
family = "AnonymicePro Nerd Font"
style = "Italic"

[font.normal]
family = "AnonymicePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[shell]
program = "/bin/bash"

[window]
decorations = "full"

[window.padding]
x = 10
y = 10
