set encoding=utf-8

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

"split nav
"nnoremap <C-J> <C-W><C-J>
"nnoremap <C-K> <C-W><C-K>
"nnoremap <C-L> <C-W><C-L>
"nnoremap <C-H> <C-W><C-H>

" Remap Vim resize commands to mimic Tmux resize keys
nnoremap <C-w>h :vertical resize -2<CR>
nnoremap <C-w>l :vertical resize +2<CR>
nnoremap <C-w>k :resize -2<CR>
nnoremap <C-w>j :resize +2<CR>

" Remap navigation between splits to Ctrl+h/j/k/l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"code folding
set foldmethod=indent
set foldlevel=99

call plug#begin()

Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'frazrepo/vim-rainbow'
Plug 'vim-syntastic/syntastic'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-scripts/indentpython.vim'
Plug 'powerline/powerline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'madox2/vim-ai'

call plug#end()

autocmd StdinReadPre * let s:std in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && v:this_session == '' | NERDTree | endif

let python_highlight_all=1
syntax on

set nu
